apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
- ingress-https.yaml
- ingress-grpc.yaml

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-cmd-params-cm.yaml
- patch-argocd-server-role.yaml
- patch-argocd-server-cluster-role.yaml
