on:
  push:
    branches:
      - main
    # ignore changes to infra/apps/api/values.auto-updated.yaml (this file is updated by the CI workflow itself)
    paths-ignore:
      - infra/apps/api/values.auto-updated.yaml
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_APP_IMAGE_NAME: "ghcr.io/whiletrue-industries/ckangpt/ckangpt-api"
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u whiletrue-industries --password-stdin &&\
          if docker pull "${DOCKER_APP_IMAGE_NAME}:latest"; then
            CACHE_FROM_ARG="--cache-from ${DOCKER_APP_IMAGE_NAME}:latest"
          else
            CACHE_FROM_ARG=""
          fi &&\
          docker build $CACHE_FROM_ARG --build-arg VERSION=${GITHUB_SHA} -t app . &&\
          docker tag app "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
          docker push "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            docker tag app "${DOCKER_APP_IMAGE_NAME}:latest" &&\
            docker push "${DOCKER_APP_IMAGE_NAME}:latest" &&\
            echo "api:" > infra/apps/api/values.auto-updated.yaml &&\
            echo "  image: ${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" >> infra/apps/api/values.auto-updated.yaml &&\
            # commit and push the updated values.auto-updated.yaml file
            git config --global user.name "ckangpt CI" &&\
            git config --global user.email "ckangpt-ci@localhost" &&\
            git add infra/apps/api/values.auto-updated.yaml &&\
            git commit -m "automatic update of ckangpt api" &&\
            git push origin main
          fi
