name: Describe datasets and save descriptions to remote storage
on:
  workflow_dispatch:
    inputs:
      dataset_domain_glob:
        description: 'Glob pattern to match CKAN domains to describe datasets from'
        required: true
        default: '*'
      dataset_name_glob:
        description: 'Glob pattern to match dataset names to describe'
        required: true
        default: '*'
  push:
    branches:
      - add-storage
env:
  DATASET_DOMAIN_GLOB: ${{ inputs.dataset_domain_glob || 'data.gov.uk' }}
  DATASET_NAME_GLOB: ${{ inputs.dataset_name_glob || '*dan-minchin-uk-records-of-ficopomatus-enigmaticus*' }}
jobs:
  build:
    environment: ori_hoch_openai
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install --upgrade pip &&\
        pip install -r requirements.txt &&\
        pip install -e .
    - env:
        OPENAI_API_KEY: ${{ secrets.ORI_HOCH_OPENAI_API_KEY }}
      run: ckangpt backend scrape-ckan-instance --save-to-storage --glob "${CKAN_INSTANCE_GLOB}"
