name: Scrape CKAN Instsances and save to remote storage
on:
  workflow_dispatch:
    inputs:
      ckan_instance_glob:
        description: 'Glob pattern to match CKAN instances to scrape'
        required: true
        default: '*'
      limit:
        description: 'Limit the number of datasets to scrape'
        required: true
        default: "0"
  push:
    branches:
      - add-storage
env:
  CKAN_INSTANCE_GLOB: ${{ inputs.ckan_instance_glob || 'data.gov.uk' }}
  LIMIT: ${{ inputs.limit || '100' }}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        pip install --upgrade pip &&\
        pip install -r requirements.txt &&\
        pip install -e .
    - run: ckangpt --debug backend scrape-ckan-instance --save-to-storage --glob --limit $LIMIT "${CKAN_INSTANCE_GLOB}"
